parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Handler\DepositCommandHandler:
        tags:
            - { name: tactician.handler, command: App\Handler\Command\DepositCommand }

    App\Handler\BetCommandHandler:
        tags:
            - { name: tactician.handler, command: App\Handler\Command\BetCommand }

    App\Handler\UserProfileCommandHandler:
        tags:
            - { name: tactician.handler, command: App\Handler\Command\UserProfileCommand }
